"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "pt" | "en" | "ru" | "et"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  pt: {
    welcome: "Bem-vindo ao meu portfolio",
    about: "Sobre Mim",
    skills: "Minhas Habilidades",
    projects: "Projetos Recentes",
    exp1Title: "Engenheiro de Software Sênior",
    exp1Company: "Riverty",
    exp1CompanyUrl: "https://riverty.com",
    exp1Location: "Tallinn, Estônia",
    exp1Period: "2022 - Presente",
    exp1Description: "Desenvolvimento de aplicações web com React e Next.js. Implementação de design systems e otimização de performance.",
    exp2Title: "Engenheiro de Software",
    exp2Company: "Arvato Financial Solutions Tech Center",
    exp2CompanyUrl: "https://arvato.com",
    exp2Location: "Tallinn, Estônia",
    exp2Period: "2022 - 2022",
    exp2Description: "Desenvolvimento de aplicações web com React e Next.js. Implementação de design systems e otimização de performance.",
    exp3Title: "Desenvolvedor Full Stack",
    exp3Company: "MAGIT IT PARTNER",
    exp3Location: "Ribeirão Preto, Brasil",
    exp3Period: "2020 - 2022",
    exp3Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp4Title: "Desenvolvedor Full Stack",
    exp4Company: "GooWe",
    exp4Location: "Ribeirão Preto, Brasil",
    exp4Period: "2019 - 2020",
    exp4Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp5Title: "Desenvolvedor Full Stack",
    exp5Company: "Kezz IT",
    exp5Location: "Ribeirão Preto, Brasil",
    exp5Period: "2019 - 2019",
    exp5Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp6Title: "Desenvolvedor Full Stack",
    exp6Company: "Onsoft Web",
    exp6Location: "Ribeirão Preto, Brasil",
    exp6Period: "2018 - 2019",
    exp6Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp7Title: "Web Freelancer",
    exp7Company: "Freelance",
    exp7Location: "Ribeirão Preto, Brasil",
    exp7Period: "2018 - 2019",
    exp7Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    skillCSharpName: "C#",
    skillCSharpCategory: "Linguagens",
    skillCSharpDescription: "Desenvolvimento de APIs RESTful escaláveis, arquitetura limpa e design patterns em .NET.",
    skillGoName: "Go",
    skillGoCategory: "Linguagens",
    skillGoDescription: "Criação de serviços backend de alta performance e concorrência eficiente.",
    skillTypeScriptName: "TypeScript",
    skillTypeScriptCategory: "Linguagens",
    skillTypeScriptDescription: "Desenvolvimento front e backend com tipagem segura e escalabilidade.",
    skillAngularName: "Angular",
    skillAngularCategory: "Frontend",
    skillAngularDescription: "Criação de aplicações SPA modulares e performáticas com RxJS e state management.",
    skillIonicName: "Ionic",
    skillIonicCategory: "Mobile",
    skillIonicDescription: "Desenvolvimento de apps híbridos com Angular e Capacitor para iOS e Android.",
    skillSwiftUIName: "SwiftUI",
    skillSwiftUICategory: "Mobile",
    skillSwiftUIDescription: "Criação de interfaces fluidas e reativas para iOS com SwiftUI e Combine.",
    skillStencilJSName: "StencilJS",
    skillStencilJSCategory: "Frontend",
    skillStencilJSDescription: "Criação de Web Components reutilizáveis e performáticos para aplicações escaláveis.",
    skillMongoDBName: "MongoDB",
    skillMongoDBCategory: "Banco de Dados",
    skillMongoDBDescription: "Modelagem e otimização de consultas em bancos NoSQL para alta escalabilidade.",
    skillSQLServerName: "SQLServer",
    skillSQLServerCategory: "Banco de Dados",
    skillSQLServerDescription: "Administração de bancos SQL, otimização de queries e procedures.",
    skillOracleName: "Oracle",
    skillOracleCategory: "Banco de Dados",
    skillOracleDescription: "Gerenciamento de grandes volumes de dados e PL/SQL para automação.",
    skillDockerName: "Docker",
    skillDockerCategory: "DevOps",
    skillDockerDescription: "Criação e orquestração de contêineres para ambientes escaláveis e isolados.",
    skillKubernetesName: "Kubernetes",
    skillKubernetesCategory: "DevOps",
    skillKubernetesDescription: "Orquestração de contêineres, autoescalabilidade e deploys resilientes.",
    skillBicepName: "Bicep",
    skillBicepCategory: "DevOps",
    skillBicepDescription: "Infraestrutura como código para provisionamento automatizado no Azure.",
    skillTerraformName: "Terraform",
    skillTerraformCategory: "DevOps",
    skillTerraformDescription: "Automação de infraestrutura multi-cloud e gerenciamento de estado.",
    projectUrlShortenerTitle: "URL-Shortener",
    projectUrlShortenerDescription: "Plataforma para encurtar URLS sendo capaz de suportar um grade volume de dados, tendo sido feito deploy na Azure.",
    projectUrlShortenerFeature1: "Geração de URLs curtas",
    projectUrlShortenerFeature2: "Redirecionamento de URLs",
    projectUrlShortenerFeature3: "Estatísticas de acesso",
    projectUrlShortenerFeature4: "Observabilidade",
    projectGcliTitle: "GCLI",
    projectGcliDescription: "CLI em Golang para criação de projetos projetos em Golang, ja contendo uma estrutura robusta e pronta para producao.",
    projectGcliFeature1: "Criação de projetos em Golang com multiplos templates",
    projectGcliFeature2: "Geração de CRUDs de formas simplificadas",
    projectGcliFeature3: "Servidor de Migration com Hot Reload",
    projectGcliFeature4: "Dockerização do projeto",
    projectGcliFeature5: "Pronto para produção",
    projectMtgCardInventoryTitle: "MTG Card Inventory",
    projectMtgCardInventoryDescription: "Aplicativo para gerenciamento de inventário e decks de cartas de Magic The Gathering.",
    projectMtgCardInventoryFeature1: "Listagem de cartas catalogadas com filtros avançados",
    projectMtgCardInventoryFeature2: "Criação de decks personalizados",
    projectMtgCardInventoryFeature3: "Sincronização com banco de dados remoto",
    projectMtgLifeCounterTitle: "MTG Life Counter",
    projectMtgLifeCounterDescription: "Aplicativo para gerenciamento de vida e histórico de partidas de Magic The Gathering.",
    projectMtgLifeCounterFeature1: "Contador de vida para até 6 jogadores",
    projectMtgLifeCounterFeature2: "Histórico de partidas",
    projectMtgLifeCounterFeature3: "Sincronização com banco de dados remoto",
    projectGcliAdvancedTemplateTitle: "GCLI Advanced Template",
    projectGcliAdvancedTemplateDescription: "Template avançado para o GCLI, contendo autenticação, autorização, testes e documentação.",
    projectGcliAdvancedTemplateFeature1: "Autenticação e autorização",
    projectGcliAdvancedTemplateFeature2: "Testes unitários e de integração",
    projectGcliAdvancedTemplateFeature3: "Documentação com Swagger",
    projectGcliAdvancedTemplateFeature4: "Dockerização",
    projectPortfolioWebsiteTitle: "Portfolio Website",
    projectPortfolioWebsiteDescription: "Site de portfolio responsivo com animações suaves e design moderno.",
    projectPortfolioWebsiteFeature1: "Animações suaves",
    projectPortfolioWebsiteFeature2: "Design responsivo",
    projectPortfolioWebsiteFeature3: "Modo escuro",
    projectPortfolioWebsiteFeature4: "Formulário de contato",
    contact: "Entre em Contato",
    viewWork: "Conheça meu trabalho",
    contactMe: "Entre em contato",
    fullstackDev: "Engenheiro de Software Sênior",
    seeProjects: "Ver projetos",
    sendMessage: "Enviar Mensagem",
    name: "Nome",
    email: "Email",
    message: "Mensagem",
    phone: "Telefone",
    location: "Localização",
    letsChat: "Vamos conversar!",
    availableFor:
      "Estou disponível para projetos freelance, oportunidades de trabalho ou apenas para trocar ideias sobre desenvolvimento web.",
    recentProjects:
      "Explore alguns dos meus trabalhos mais recentes, demonstrando minhas habilidades em desenvolvimento web full-stack.",
    mainFeatures: "Principais recursos:",
    seeMoreGithub: "Ver mais no GitHub",
    checkoutMyLinkedIn: "LinkedIn",
    fromYear: "0",
    untilYear: "Anos",
    skillDetails: "Detalhes",
    proficiencyLevel: "Tempo de experiência",
    description: "Descrição",
    clickSkill: "Clique em uma habilidade para ver mais detalhes",
    transformingIdeas: "Transformando ideias em experiências digitais excepcionais",
    frontendDev: "Desenvolvimento Frontend",
    backendDev: "Desenvolvimento Backend",
    database: "Banco de Dados",
    fullWebApps: "Aplicações Web Completas",
    yearsExperience: "anos de experiência",
    seniorAchievement1: "Liderança técnica em projetos de grande escala",
    seniorAchievement2: "Arquitetura de soluções escaláveis e resilientes",
    seniorAchievement3: "Mentoria de desenvolvedores e equipes",
    keyAchievements: "Principais Conquistas",
    careerJourney: "Trajetória Profissional",
    professionalExperience: "Experiência Profissional",
    experienceDescription:
      "Minha jornada profissional inclui trabalho com empresas inovadoras, liderando projetos desafiadores e entregando soluções de alta qualidade.",
    showMore: "Ver mais detalhes",
    showLess: "Mostrar menos",
    discussYourProject: "Vamos discutir seu projeto",
    responsibilities: "Responsabilidades",
    aboutServiceFrontend: "Criação de interfaces modernas e responsivas com React, Next.js e Tailwind CSS.",
    aboutServiceBackend: "Construção de APIs robustas e escaláveis com Node.js, Express e TypeScript.",
    aboutServiceDatabase: "Modelagem e otimização de bancos de dados SQL e NoSQL.",
    aboutServiceFullWebApps: "Desenvolvimento full-stack de aplicações web de ponta a ponta.",
    aboutIntro1: "Olá! Sou um desenvolvedor FullStack apaixonado por criar soluções web elegantes e funcionais.",
    aboutIntro2: "Olá, me chamo Vinicius. Atualmente trabalho com Stencil e .NET Core em uma empresa financeira. Uma das minhas atividades favoritas no tempo livre (além de tocar guitarra) é criar novas arquiteturas para me desafiar com novos padrões de desenvolvimento. Além disso, um dos meus hobbies é aprender novas stacks, por exemplo, agora estou bastante interessado em Golang.",
    aboutIntro3: "Nos últimos anos também tenho me interessado por aprender novos idiomas e culturas, especialmente as nórdicas. Você pode me contatar por e-mail, e se quiser ver meus projetos pessoais, confira a seção de projetos.",
  },
  en: {
    welcome: "Welcome to my portfolio",
    about: "About Me",
    skills: "My Skills",
    aboutServiceFrontend: "Creating modern and responsive interfaces with React, Next.js and Tailwind CSS.",
    aboutServiceBackend: "Building robust and scalable APIs with Node.js, Express and TypeScript.",
    aboutServiceDatabase: "Modeling and optimizing SQL and NoSQL databases.",
    aboutServiceFullWebApps: "Full-stack development of end-to-end web applications.",
    aboutIntro1: "Hello! I'm a FullStack developer passionate about creating elegant and functional web solutions.",
    aboutIntro2: "Hi, I'm Vinicius. Currently working with Stencil and .NET Core at a financial company. One of my favorite things to do on my free time (besides playing the guitar) is to build new architectures in order to challenge myself with new development patterns. Besides, one of my hobbies includes learning new stacks, for instance, right now I'm quite interested in Golang.",
    aboutIntro3: "For the past few years I've also been interested in learning new languages and cultures, especially the nordic ones. You can reach me at my e-mail, if you want to see my personal projects, check out projects section.",
    projects: "Recent Projects",
    exp1Title: "Senior Software Engineer",
    exp1Company: "Riverty",
    exp1CompanyUrl: "https://riverty.com",
    exp1Location: "Tallinn, Estonia",
    exp1Period: "2022 - Present",
    exp1Description: "Web application development with React and Next.js. Design system implementation and performance optimization.",
    exp2Title: "Software Engineer",
    exp2Company: "Arvato Financial Solutions Tech Center",
    exp2CompanyUrl: "https://arvato.com",
    exp2Location: "Tallinn, Estonia",
    exp2Period: "2022 - 2022",
    exp2Description: "Web application development with React and Next.js. Design system implementation and performance optimization.",
    exp3Title: "Full Stack Developer",
    exp3Company: "MAGIT IT PARTNER",
    exp3Location: "Ribeirão Preto, Brazil",
    exp3Period: "2020 - 2022",
    exp3Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp4Title: "Full Stack Developer",
    exp4Company: "GooWe",
    exp4Location: "Ribeirão Preto, Brazil",
    exp4Period: "2019 - 2020",
    exp4Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp5Title: "Full Stack Developer",
    exp5Company: "Kezz IT",
    exp5Location: "Ribeirão Preto, Brazil",
    exp5Period: "2019 - 2019",
    exp5Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp6Title: "Full Stack Developer",
    exp6Company: "Onsoft Web",
    exp6Location: "Ribeirão Preto, Brazil",
    exp6Period: "2018 - 2019",
    exp6Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp7Title: "Web Freelancer",
    exp7Company: "Freelance",
    exp7Location: "Ribeirão Preto, Brazil",
    exp7Period: "2018 - 2019",
    exp7Description: "Development of responsive websites and landing pages for clients from various sectors.",
    skillCSharpName: "C#",
    skillCSharpCategory: "Languages",
    skillCSharpDescription: "Development of scalable RESTful APIs, clean architecture, and design patterns in .NET.",
    skillGoName: "Go",
    skillGoCategory: "Languages",
    skillGoDescription: "Building high-performance backend services and efficient concurrency.",
    skillTypeScriptName: "TypeScript",
    skillTypeScriptCategory: "Languages",
    skillTypeScriptDescription: "Frontend and backend development with safe typing and scalability.",
    skillAngularName: "Angular",
    skillAngularCategory: "Frontend",
    skillAngularDescription: "Building modular and performant SPA applications with RxJS and state management.",
    skillIonicName: "Ionic",
    skillIonicCategory: "Mobile",
    skillIonicDescription: "Hybrid app development with Angular and Capacitor for iOS and Android.",
    skillSwiftUIName: "SwiftUI",
    skillSwiftUICategory: "Mobile",
    skillSwiftUIDescription: "Creating fluid and reactive interfaces for iOS with SwiftUI and Combine.",
    skillStencilJSName: "StencilJS",
    skillStencilJSCategory: "Frontend",
    skillStencilJSDescription: "Building reusable and performant Web Components for scalable applications.",
    skillMongoDBName: "MongoDB",
    skillMongoDBCategory: "Database",
    skillMongoDBDescription: "Modeling and optimizing queries in NoSQL databases for high scalability.",
    skillSQLServerName: "SQLServer",
    skillSQLServerCategory: "Database",
    skillSQLServerDescription: "SQL database administration, query and procedure optimization.",
    skillOracleName: "Oracle",
    skillOracleCategory: "Database",
    skillOracleDescription: "Managing large volumes of data and PL/SQL for automation.",
    skillDockerName: "Docker",
    skillDockerCategory: "DevOps",
    skillDockerDescription: "Creating and orchestrating containers for scalable and isolated environments.",
    skillKubernetesName: "Kubernetes",
    skillKubernetesCategory: "DevOps",
    skillKubernetesDescription: "Container orchestration, autoscaling, and resilient deployments.",
    skillBicepName: "Bicep",
    skillBicepCategory: "DevOps",
    skillBicepDescription: "Infrastructure as code for automated provisioning on Azure.",
    skillTerraformName: "Terraform",
    skillTerraformCategory: "DevOps",
    skillTerraformDescription: "Multi-cloud infrastructure automation and state management.",
    projectUrlShortenerTitle: "URL-Shortener",
    projectUrlShortenerDescription: "Platform for shortening URLs, capable of supporting a large volume of data, deployed on Azure.",
    projectUrlShortenerFeature1: "Short URL generation",
    projectUrlShortenerFeature2: "URL redirection",
    projectUrlShortenerFeature3: "Access statistics",
    projectUrlShortenerFeature4: "Observability",
    projectGcliTitle: "GCLI",
    projectGcliDescription: "CLI in Golang for creating Golang projects, already containing a robust and production-ready structure.",
    projectGcliFeature1: "Create Golang projects with multiple templates",
    projectGcliFeature2: "Simplified CRUD generation",
    projectGcliFeature3: "Migration server with Hot Reload",
    projectGcliFeature4: "Project Dockerization",
    projectGcliFeature5: "Production ready",
    projectMtgCardInventoryTitle: "MTG Card Inventory",
    projectMtgCardInventoryDescription: "App for managing Magic The Gathering card inventory and decks.",
    projectMtgCardInventoryFeature1: "Cataloged card listing with advanced filters",
    projectMtgCardInventoryFeature2: "Custom deck creation",
    projectMtgCardInventoryFeature3: "Remote database sync",
    projectMtgLifeCounterTitle: "MTG Life Counter",
    projectMtgLifeCounterDescription: "App for managing life and match history for Magic The Gathering.",
    projectMtgLifeCounterFeature1: "Life counter for up to 6 players",
    projectMtgLifeCounterFeature2: "Match history",
    projectMtgLifeCounterFeature3: "Remote database sync",
    projectGcliAdvancedTemplateTitle: "GCLI Advanced Template",
    projectGcliAdvancedTemplateDescription: "Advanced template for GCLI, including authentication, authorization, tests, and documentation.",
    projectGcliAdvancedTemplateFeature1: "Authentication and authorization",
    projectGcliAdvancedTemplateFeature2: "Unit and integration tests",
    projectGcliAdvancedTemplateFeature3: "Swagger documentation",
    projectGcliAdvancedTemplateFeature4: "Dockerization",
    projectPortfolioWebsiteTitle: "Portfolio Website",
    projectPortfolioWebsiteDescription: "Responsive portfolio website with smooth animations and modern design.",
    projectPortfolioWebsiteFeature1: "Smooth animations",
    projectPortfolioWebsiteFeature2: "Responsive design",
    projectPortfolioWebsiteFeature3: "Dark mode",
    projectPortfolioWebsiteFeature4: "Contact form",
    contact: "Contact Me",
    viewWork: "View my work",
    contactMe: "Contact me",
    fullstackDev: "Senior Software Engineer",
    seeProjects: "See projects",
    sendMessage: "Send Message",
    name: "Name",
    email: "Email",
    message: "Message",
    phone: "Phone",
    location: "Location",
    letsChat: "Let's chat!",
    availableFor:
      "I'm available for freelance projects, job opportunities, or just to exchange ideas about web development.",
    recentProjects: "Explore some of my recent work, showcasing my skills in full-stack web development.",
    mainFeatures: "Main features:",
    seeMoreGithub: "See more on GitHub",
    checkoutMyLinkedIn: "LinkedIn",
    fromYear: "0",
    untilYear: "Years",
    skillDetails: "Details",
    proficiencyLevel: "Experience Time",
    description: "Description",
    clickSkill: "Click on a skill to see more details",
    transformingIdeas: "Transforming ideas into exceptional digital experiences",
    frontendDev: "Frontend Development",
    backendDev: "Backend Development",
    database: "Database",
    fullWebApps: "Full Web Applications",
    yearsExperience: "years of experience",
    seniorAchievement1: "Technical leadership in large-scale projects",
    seniorAchievement2: "Architecture of scalable and resilient solutions",
    seniorAchievement3: "Mentoring developers and teams",
    keyAchievements: "Key Achievements",
    careerJourney: "Career Journey",
    professionalExperience: "Professional Experience",
    experienceDescription:
      "My professional journey includes work with innovative companies, leading challenging projects and delivering high-quality solutions.",
    showMore: "Show more details",
    showLess: "Show less",
    discussYourProject: "Let's discuss your project",
    responsibilities: "Responsibilities",
  },
  ru: {
    welcome: "Добро пожаловать в мое портфолио",
    about: "Обо мне",
    skills: "Мои навыки",
    projects: "Недавние проекты",
    contact: "Связаться со мной",
    viewWork: "Посмотреть мои работы",
    contactMe: "Связаться со мной",
    fullstackDev: "Старший инженер-программист",
    seeProjects: "Посмотреть проекты",
    sendMessage: "Отправить сообщение",
    name: "Имя",
    email: "Электронная почта",
    message: "Сообщение",
    phone: "Телефон",
    location: "Местоположение",
    letsChat: "Давайте пообщаемся!",
    availableFor: "Я доступен для фриланс-проектов, предложений работы или просто для обмена идеями о веб-разработке.",
    recentProjects: "Изучите некоторые из моих последних работ, демонстрирующих мои навыки в фулстек веб-разработке.",
    mainFeatures: "Основные функции:",
    seeMoreGithub: "Смотреть больше на GitHub",
    checkoutMyLinkedIn: "Посмотреть мой LinkedIn",
    aboutServiceFrontend: "Создание современных и адаптивных интерфейсов с помощью React, Next.js и Tailwind CSS.",
    aboutServiceBackend: "Разработка надёжных и масштабируемых API с Node.js, Express и TypeScript.",
    aboutServiceDatabase: "Моделирование и оптимизация SQL и NoSQL баз данных.",
    aboutServiceFullWebApps: "Full-stack разработка веб-приложений от начала до конца.",
    aboutIntro1: "Привет! Я FullStack разработчик, увлечённый созданием элегантных и функциональных веб-решений.",
    aboutIntro2: "Привет, я Винисиус. Сейчас работаю со Stencil и .NET Core в финансовой компании. В свободное время (кроме игры на гитаре) люблю строить новые архитектуры, чтобы бросать себе вызов новыми паттернами разработки. Также мне нравится изучать новые стеки, например, сейчас интересуюсь Golang.",
    aboutIntro3: "В последние годы я также интересуюсь изучением новых языков и культур, особенно северных. Связаться со мной можно по e-mail, а если хотите увидеть мои личные проекты — смотрите раздел проектов.",
    fromYear: "0",
    untilYear: "Лет",
    skillDetails: "Детали",
    proficiencyLevel: "Время опыта",
    description: "Описание",
    clickSkill: "Нажмите на навык, чтобы увидеть более подробную информацию",
    transformingIdeas: "Превращаю идеи в исключительный цифровой опыт",
    frontendDev: "Фронтенд-разработка",
    backendDev: "Бэкенд-разработка",
    database: "Базы данных",
    fullWebApps: "Полные веб-приложения",
    yearsExperience: "лет опыта",
    seniorAchievement1: "Техническое руководство в крупномасштабных проектах",
    seniorAchievement2: "Архитектура масштабируемых и отказоустойчивых решений",
    seniorAchievement3: "Наставничество разработчиков и команд",
    careerJourney: "Карьерный путь",
    professionalExperience: "Профессиональный опыт",
    experienceDescription:
      "Мой профессиональный путь включает работу с инновационными компаниями, руководство сложными проектами и предоставление высококачественных решений.",
    keyAchievements: "Ключевые достижения",
    showMore: "Показать больше деталей",
    showLess: "Показать меньше",
    discussYourProject: "Давайте обсудим ваш проект",
    responsibilities: "Обязанности",
  },
  et: {
    welcome: "Tere tulemast minu portfooliosse",
    about: "Minust",
    skills: "Minu oskused",
    projects: "Viimased projektid",
    contact: "Võta ühendust",
    viewWork: "Vaata minu tööd",
    contactMe: "Võta minuga ühendust",
    fullstackDev: "Vanemtarkvarainsener",
    seeProjects: "Vaata projekte",
    sendMessage: "Saada sõnum",
    name: "Nimi",
    email: "E-post",
    message: "Sõnum",
    phone: "Telefon",
    location: "Asukoht",
    letsChat: "Räägime!",
    availableFor:
      "Olen saadaval vabakutseliste projektide, tööpakkumiste jaoks või lihtsalt veebiarenduse ideede vahetamiseks.",
    recentProjects: "Tutvu mõnede minu viimaste töödega, mis näitavad minu oskusi täistekkide veebiarenduses.",
    mainFeatures: "Peamised funktsioonid:",
    seeMoreGithub: "Vaata rohkem GitHubis",
    checkoutMyLinkedIn: "Vaata minu LinkedIni",
    fromYear: "0",
    aboutServiceFrontend: "Moodsaid ja reageerivaid liideseid Reacti, Next.js-i ja Tailwind CSS-iga.",
    aboutServiceBackend: "Tugevate ja skaleeritavate API-de loomine Node.js, Expressi ja TypeScriptiga.",
    aboutServiceDatabase: "SQL ja NoSQL andmebaaside modelleerimine ja optimeerimine.",
    aboutServiceFullWebApps: "Täistekkide veebirakenduste arendamine algusest lõpuni.",
    aboutIntro1: "Tere! Olen FullStack arendaja, kelle kirg on luua elegantseid ja funktsionaalseid veebilahendusi.",
    aboutIntro2: "Tere, mina olen Vinicius. Töötan praegu Stenciliga ja .NET Core'iga finantsettevõttes. Vabal ajal (peale kitarri mängimise) meeldib mulle ehitada uusi arhitektuure, et end proovile panna uute arendusmustritega. Lisaks on minu hobiks uute stackide õppimine, näiteks praegu huvitab mind Golang.",
    aboutIntro3: "Viimastel aastatel olen huvitunud ka uute keelte ja kultuuride õppimisest, eriti põhjamaistest. Võid minuga ühendust võtta e-posti teel, kui tahad näha minu isiklikke projekte, vaata projektide sektsiooni.",
    untilYear: "Aastat",
    skillDetails: "Üksikasjad",
    proficiencyLevel: "Kogemuse aeg",
    description: "Kirjeldus",
    clickSkill: "Lisateabe lugemiseks klõpsake oskusel",
    transformingIdeas: "Muudan ideed erakordseteks digitaalseteks kogemusteks",
    frontendDev: "Frontendi arendus",
    backendDev: "Backendi arendus",
    database: "Andmebaasid",
    fullWebApps: "Täielikud veebirakendused",
    yearsExperience: "aastat kogemust",
    seniorAchievement1: "Tehniline juhtimine suuremahulistes projektides",
    seniorAchievement2: "Skaleeritavate ja vastupidavate lahenduste arhitektuur",
    seniorAchievement3: "Arendajate ja meeskondade juhendamine",
    keyAchievements: "Peamised saavutused",
    careerJourney: "Karjääritee",
    professionalExperience: "Töökogemus",
    experienceDescription:
      "Minu professionaalne teekond hõlmab tööd innovaatiliste ettevõtetega, keeruliste projektide juhtimist ja kvaliteetsete lahenduste pakkumist.",
    showMore: "Näita rohkem üksikasju",
    showLess: "Näita vähem",
    discussYourProject: "Arutame teie projekti",
    responsibilities: "Kohustused",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

